### ISSUE TITLE
This repository should be a fork

### ISSUE THREAD

**Issue by chrisseaton** [mmtk/ruby-old#6]
I for example can't open a PR from my fork of Ruby. It also doesn't tell me how behind upstream it is.

**Comment by wks** [comment]
GitHub does not support changing the upstream of a repo.  But I will do the following:

1.  Rename the current repo `mmtk/ruby` to `mmtk/ruby-old`.
2.  Fork the official repo `ruby/ruby` to `mmtk/ruby`.
3.  Push my branches back to `mmtk/ruby`.

After these steps, `mmtk/ruby` on the GitHub server will be considered a fork of `ruby/ruby`, but we don't need to do any configuration on the client side.

**Comment by wks** [comment]
Done.  The repository URL remains to be https://github.com/mmtk/ruby, but this issue is now in mmtk/old-ruby.  If things don't go wrong, I'll remove mmtk/old-ruby later.
